# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31f7a2d1cbe2e1f3be9104104c33e9048562074b43b5d81a9256677c495572724c0a7fd9879385a9461465da7f97115f5a8bd537baea4ca50825714254b6b868

test:
  secret_key_base: fb9cc280e5ecf490902255e5219297486beb9da0460d6db58093955f26c7cb4a30a72cfd70f8ee40d91175cc5eb09315799299a2225e508a71dd4822d31aac77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
